### ISSUE TITLE
Xillia Cheat Table - Multiplayer Link cheat does not work

### ISSUE THREAD

**Issue by gunstarsign** [Sora3100/Tales_of_Cheat_Tables#1]
Attempted to use option [Allow Player control while linked] in NPUB31136 version of Xillia.

When option is enabled, dropdown menu for [READ THIS], [Newer CPUs] and [Sandy Bridge] appear, but linking with human 2P does not yield expected results.
When attempting to enable [Newer CPUs] or [Sandy Bridge] options, Cheat Engine becomes slow and unresponsive briefly before returning to normal, but neither will enable by clicking checkbox.
Cannot link with human players.

**Comment by Sora3100** [comment]
Are you using this specific version of the emulator: rpcs3 0.0.12-10883-92d65ff3 Alpha?

Newer versions of the emulator unfortunately breaks the scripts.

**Comment by Sora3100** [comment]
Is this still a problem? I'll close this issue soon otherwise,

**Comment by Rogus** [comment]
> Are you using this specific version of the emulator: rpcs3 0.0.12-10883-92d65ff3 Alpha?
> 
> Newer versions of the emulator unfortunately breaks the scripts.

There's no other way to use another kind of address only static ones?

**Comment by gunstarsign** [comment]
>Is this still a problem?
No. Using the version you told me, I was able to gt it working.
My apologies, and thank you again for the help.

**Comment by Sora3100** [comment]
> > Are you using this specific version of the emulator: rpcs3 0.0.12-10883-92d65ff3 Alpha?
> > Newer versions of the emulator unfortunately breaks the scripts.
> 
> There's no other way to use another kind of address only static ones?

Unfortunately, not in an emulator. If the game had a native port, then I could use pointers instead.

> > Is this still a problem?
> 
> No. Using the version you told me, I was able to gt it working.
> My apologies, and thank you again for the help.

Ah, nice! Enjoy!
