### ISSUE TITLE
Tales of Destiny DC

### ISSUE THREAD

**Issue by Mikeyjanuary11** [Sora3100/Tales_of_Cheat_Tables#15]
I just found the ToD:DC translation and decided to try your CT with it.  The values keep fluctuating when I hooked PCSX2.  Is there a way to fix this or is it because of the translation patch that's making it screwy?

**Comment by Sora3100** [comment]
If you are using the latest developer version of PCSX2, the addresses all moved from 2xxxxxxx to 4xxxxxxx due to the 64-bit update.
See https://github.com/PCSX2/pcsx2/pull/3644
As a workaround, you can manually double click on each header/group's address, and change the first digit from 2 to 4.
Alternatively, you can also downgrade.

**Comment by Mikeyjanuary11** [comment]
I tried the first method of manually changing the first digit from 2 to 4.  The values stopped fluctuating but they're all displaying 0 now.  Nothing in-game changes when I set a value in the CT.

**Comment by Sora3100** [comment]
Are you sure you're doing it correctly? This is how it is default. The address is "202C2E90"
![image](https://user-images.githubusercontent.com/18172557/129613292-844c18da-5394-4f20-bdde-5acc689a78c2.png)
It should become like this. "402C2E90"
![image](https://user-images.githubusercontent.com/18172557/129613383-51892660-a66c-4964-a4a8-74f2f44aa628.png)

I just tested myself with the latest patch and they seem to be working.

**Comment by Mikeyjanuary11** [comment]
Yes, that's exactly how I edited the table this morning.

![image](https://user-images.githubusercontent.com/83097061/129654512-2d68cb52-e205-4741-b0f0-11673369455d.png)

**Comment by Sora3100** [comment]
Huh, and nothing appears properly?
What version of PCSX2, what version of the patch are you running?

**Comment by Mikeyjanuary11** [comment]
CE isn't detecting the values already in the game and changing them in the table does nothing either.

PCSX2 1.7.0-20210815080234
The patch version is v0.0.216.  v0.0.217 just got released several hours ago, so I'm going to update in a little bit.

**Comment by Sora3100** [comment]
Okay, are you running Windows?
And can you try replacing the first digit of the addresses from 1 to 20?
If that doesn't work, I am honestly unsure. It works on PCSX2 1.7.0-dev-1612-g1180de51f and patch v0.0.216

**Comment by Mikeyjanuary11** [comment]
Sorry for the late response.

Changing the first digit to 3 worked for all of them.  Thanks!

This makes me also wonder if you have an index of item values on hand already.  Another problem I ran into was when I tried to edit in an accessory for any character, it would work but then I'd end up with x255 of that item in particular in my inventory.  Do you know why this happens or how I can make that not happen?

**Comment by Sora3100** [comment]
Unfortunately, I don't have an item list. It would be in the table already otherwise. Most I could offer is a Japanese one, but I am unsure if even they have a list.
I am not sure how you're ending up with 255. Are you adding the item to one of the character's accessory then removing it? Or are you editing the inventory directly?

**Comment by Mikeyjanuary11** [comment]
I'm using the equipment editor.  For example, if I take the value for Stahn's accessory and put it into Mary's, which is currently empty, it'll work:
![image](https://user-images.githubusercontent.com/83097061/129951877-1b3a1bf8-04c3-44cc-9c50-41dab13debe1.png)

The problem is I'll get x255 of that accessory in my inventory:
![image](https://user-images.githubusercontent.com/83097061/129952077-ce0ae3dd-5bd6-423c-a052-3e5b7dd9290b.png)

**Comment by Sora3100** [comment]
So, you have say "770" as an accessory for Stahn, Mary for example has no rings equipped (both show 0), and you put in 770 to one of them, and that gives you 255? I cannot reproduce this.

**Comment by Mikeyjanuary11** [comment]
It's happening repeatedly on my end.  I changed the first digit of the address back to 4 for the equipment editor and tried putting "769" into Mary's Ring 1 again.  For whatever reason, it's giving me the same result as when the first digit was 3.

**Comment by Sora3100** [comment]
Can you test if it happens on the vanilla game? Or a fresh save?

**Comment by Mikeyjanuary11** [comment]
Same thing with vanilla game.  The equipment can only be edited if the first digit of the address is 3 but not 4 now:
![image](https://user-images.githubusercontent.com/83097061/129959098-5304092b-81f2-428d-ac9a-e0641a89937c.png)
![image](https://user-images.githubusercontent.com/83097061/129959146-f41f01aa-46b6-44e5-a91b-8bea51a6d904.png)

**Comment by Sora3100** [comment]
Can you write a step-by-step on what you do?

**Comment by Mikeyjanuary11** [comment]
1. Open CT
2. Hook CE to PCSX2
3. Load ISO
4. Load state or save
5. Change Mary's Ring 1 from 0 to 769 in Equipment Editor
6. Activate
7. Check for change in game
8. Deactivate

**Comment by Sora3100** [comment]
Yeah, I still cannot recreate this. Any reason for step 6 and 8 though? Those are completely pointless.

**Comment by Mikeyjanuary11** [comment]
It's okay, no biggie.

I was trying to change stats again using the table last night and I had to switch the first digit of the addresses from 3 to 4 for them to work.  It's very peculiar.  I'd like to say every condition was the same when I loaded up since I didn't update the emulator and I'm still at the same point in the game.

**Comment by Sora3100** [comment]
The update I just submitted may help with your issue of addresses changing, it should thereotically be automated now. Hopefully that helps!

**Comment by Mikeyjanuary11** [comment]
Very cool, thank you!

**Comment by Sora3100** [comment]
There wasn't, but now there is!

**Comment by Mikeyjanuary11** [comment]
Very nice!

The device points reset to their original value if CE is disabled.  I noticed the same behavior when I tried using AR codes to modify them.  Does this happen on your end?

**Comment by Sora3100** [comment]
Yes, it does. Freeze the value and you'll be able to enable them all. It's just simply how the game works.

**Comment by Mikeyjanuary11** [comment]
In a future update, could I suggest adding a Lens Modifier? :)

**Comment by Sora3100** [comment]
Yes, next update will have it.

**Comment by Sora3100** [comment]
Sorry about taking so long. Do you still have any issues, or can this be closed?

**Comment by Mikeyjanuary11** [comment]
Thank you for the Lens update!!

Sure, you can close it.  Do you have Discord?  Maybe I can hit you up there in the future.

**Comment by Sora3100** [comment]
Yeah, I do, but I am under a different name.
My handle is Meebo#7954
