### ISSUE TITLE
Can you permaedit the stats and the other editing options?

### ISSUE THREAD

**Issue by Rogus** [Sora3100/Tales_of_Cheat_Tables#23]
I would like of a faster way of registering the devil's arms kill editor. Can it be accomplished? Or is an engine related thing? Like encrypted thing, thanks for your hard work

**Comment by Sora3100** [comment]
I'm not sure what you mean of a faster way of registering, is ctrl/shiftclicking the 6 entries and typing in the number not fast enough?

**Comment by Sora3100** [comment]
Is this still a problem? If not, I'll close the issue

**Comment by Rogus** [comment]
I encountered another issue with the devil weapons they are all ?? and are not markable with the Cross red X, so therefore I cannot edit the counter kills anymore.
Can you help meebo?
