### ISSUE TITLE
Tales of Destiny DC

### ISSUE THREAD

**Issue by Gunlaus** [Sora3100/Tales_of_Cheat_Tables#38]
Could you direct me to where you got the Tales of Destiny DC cheat table?

**Comment by Sora3100** [comment]
I am not sure what you mean? All the tables you see here are made by me.

**Comment by Gunlaus** [comment]
Oh? In that case, were you able to figure out the debug menu code for Tales of destiny DC? 
(Excellent work btw)

**Comment by Sora3100** [comment]
What debug menu are you referring to? I'm only aware of a minigame screenshot existing within the game's files that shows a debug menu for it, and a random debug room I've found by accident.

**Comment by Gunlaus** [comment]
Like the one in Eternia that lets you teleport to any location/event-location. (I'm wondering if Destiny DC even has that feature in its debug menu)

**Comment by Sora3100** [comment]
I'm not aware of any debug menu existing in retail releases of Destiny DC. I don't think there are even strings left for it.

**Comment by Gunlaus** [comment]
Ah, I see. Thanks for clearing that up.
