### ISSUE TITLE
how to use arte properties (tales of graces f)

### ISSUE THREAD

**Issue by aspendable** [Sora3100/Tales_of_Cheat_Tables#41]
![image](https://user-images.githubusercontent.com/37377938/169678956-0421c1a4-7a55-4f4b-9591-f4621e5a23c4.png)

how to edit those arrays, i wanted to edit quick slash to 0 cc cost

**Comment by Sora3100** [comment]
You need to double click on the header's address (the arte properties group), then you need to change the letter after the * to whatever arte you want (it should be the same as the arte list-+1)
![image](https://user-images.githubusercontent.com/18172557/169681616-3352799f-31d1-4ae9-a854-6d1d9cc57100.png)
