### ISSUE TITLE
Tales of the Abyss btsk 

### ISSUE THREAD

**Issue by EnthusiasticEnthusiast** [Sora3100/Tales_of_Cheat_Tables#43]
Hello, i'm currently using the cheat table you've created for Tales of the Abyss. I've noticed that only a very limited amount of artes are allowed to have things like hit stun and cooldown edited. This being Luke and only fang blade, rending thrust, and his aerial attacks. I was wondering if it's possible for you to make more characters' artes available to be edited in the same fashion. If you plan to add this in an update down the line that's perfectly fine, or if you would be alright with telling me how to add these features myself I would be alright with that too. Of course, as long as it's okay with you, thank you for your time!

**Comment by Sora3100** [comment]
I do not plan to update that, as it doesn't seem to follow a format, and it would take a very long time for something that barely any people will use.

That being said, you can use this quick how-to to get more for yourself:
If you click on Fang Blade, press F5 on it, then use Fang Blade to hit someone, click on the entry that appeared in the new window, click show disassembly, then in the new window right click the highlighted part in the top part of the window, then right click and click "Find out what addresses this instruction accesses", then use whatever attack/arte you want to change, and it'll appear in the newest window.
