### ISSUE TITLE
Tales of Xillia 2 CT

### ISSUE THREAD

**Issue by Mikeyjanuary11** [Sora3100/Tales_of_Cheat_Tables#5]
Most of the table for ToX2 works except for

- Rideaux & Ivar Fight Editor
- Chronos (Canaan) Fight Editor
- Arena Editor
- Gald Finder
- Chromatus Gauge Finder
- Overlimit Gauge Finder
- Difficulty Finder

The above just have <script> under value and their boxes can't be checked.

**Comment by Sora3100** [comment]
Are you using the listed RPCS3 version? The newer versions change some things.
If you are, do you have MEM_MAPPED enabled in settings? It's under Scan Settings.

**Comment by Mikeyjanuary11** [comment]
> Are you using the listed RPCS3 version? The newer versions change some things.
> If you are, do you have MEM_MAPPED enabled in settings? It's under Scan Settings.

I'm actually just using the latest builds from the auto updates.
I didn't have MEM_MAPPED checked.  That fixed problem mostly.  The only entry that still doesn't open is the Chromatus Gauge Finder.

**Comment by Sora3100** [comment]
Yeah, the latest builds will break the scripts, so I can't really do much about that.
