### ISSUE TITLE
Player control while linked not working ( X1 & X2 )

### ISSUE THREAD

**Issue by Gainwirf** [Sora3100/Tales_of_Cheat_Tables#57]
I'm having a lot of trouble using the link mp script on my main build ( ryzen 5800x )
The old table's sandy bridge version of the script was working fine
The script works perfectly on my second build though ( i5 7400 )
I'm using the newest table version and the correct emulator build

Please help

**Comment by Sora3100** [comment]
That is weird, do you have a Discord? I will need you to follow instructions to check what is wrong.
