### ISSUE TITLE
Tales of Graces F [BLES01617]

### ISSUE THREAD

**Issue by IngwiePhoenix** [Sora3100/Tales_of_Cheat_Tables#6]
Hello!

I am on the lookout for a cheat table that might work with the european version of Tales of Graces F. Now, I am not all that experienced in the usage of Cheat Tables. How would I go about using the ToGF table that you provided - and if it does not work, how may I find the Gald alue on my own?

Basically, me and my friends are playing in co-op via Parsec on RPCS3 and we are only left with the money related titles...so, we'd love to skip them if possible.

Got any hint? Thanks :)

Kind regards,
Ingwie

**Comment by Sora3100** [comment]
Unfortunately the only real thing my table provides for Graces is the party formation, as explained in the readme.
As for how you'd find Gald, you would have to search in 4 byte big endian the current amount you have, sell/buy something so your gald changes, search for that amount, and keep repeating this until you got it down to 1 address.
Note that if the game is like Xillia 2, where the address for gald changes, you might have to find it again on a restart of the game.
