### ISSUE TITLE
Requests ToX2

### ISSUE THREAD

**Issue by Sownatta** [Sora3100/Tales_of_Cheat_Tables#67]
First of all, amazing stuff.

Here's my humble request list:

Custom charge time on power charge 1, 2 and 3 ( if custom isn't possible, then 0.5 seconds per charge will do ).
Dual Waltz / Endless Waltz after the first combo hit or over Zero Divide.
Chromatus keeps the party.

I couldn't help but notice that Victor was added to the table. 
Dunno if this is possible, but i'll ask anyway.

Add his mystic arte's portrait on both normal and chromatus form.
I think it would be nice if you added Victor's original Form Destroyer, because his voice is currently being cut by the animation flow.
Knowing how difficult adding a different mystic arte can be, maybe you could just slap some basic attack screams over the initial speech, like Ludger's Form Destroyer.
Since Victor shouldn't be able to use Eternal Waltz, i think you should keep Form Destroyer even at chromatus lv 4.
That would create the perfect playable character.

Sorry for this huge mess LOL.

**Comment by Sora3100** [comment]
Custom charge is already possible, you just have to use the skill properties editor (that being said I don't remember if it's hidden under notes)
Dual Waltz/Endless Waltz is probably possible, but I don't think I'm implementing it on emulator, as it would be tied to the emulator
For Chromatus keeping party, I'm not sure this is possible with my current knowledge. It is very likely to be part of the arte's script, which I have no way of reading.
Unfortunately, the same applies for Victor stuff. It's possible, but it would require a script that modifies game code, which with emulator it's harder than a native PC port.

**Comment by Sownatta** [comment]
That's unfortunate. if you ever change your mind, i'll be looking forward to these changes.
Thank you for being so kind and explaining everything.
