### ISSUE TITLE
ToSDotNW Emil Spells

### ISSUE THREAD

**Issue by LeonTrifang** [Sora3100/Tales_of_Cheat_Tables#72]
So my goal is to turn Emil into a spell caster, and funny enough an animation plays when he starts casting, but it's his taming animation so the camera zooms in on him just like when he is taming. I was wondering if you know of a way to fix this? I know this is a long shot, but if you know anything that could help I am willing to try to learn!

**Comment by Sora3100** [comment]
Unfortunately I have nothing for that.

**Comment by LeonTrifang** [comment]
No worries, I found another issue this one with Graces, but lemme just check and make sure you didn't cover it already.
