### ISSUE TITLE
Graces crash upon arte edit

### ISSUE THREAD

**Issue by LeonTrifang** [Sora3100/Tales_of_Cheat_Tables#73]
When I edit Malik's B artes by adding Sophie's first aid, it doesn't crash the game and he can use it just fine, but the second I go into his arte list in game, it crashes. Any fix for this or such? Can the game just not register that spell on that character? Also when giving them their own spells it's fine, also using Fairy Circle on Malik crashed the game. Is the game just coded harder than the others and doesn't like this type of stuff and can't register it?

**Comment by Sora3100** [comment]
I am unsure, it doesn't crash if you don't directly hover over it though. I assume in the case of using it something doesn't exist for  Malik specifically and the game doesn't like it.

**Comment by LeonTrifang** [comment]
It seems to just happen when you add an arte that they shouldn't have for any character. I tested it on Hubert too, but Hubert can use some that Malik can't like Fairy Circle. I can just not open the arte menu for them, sorry to bother you again, but is a title editor possible too? That way I can teach them the arte and have them use it even if I switch characters. If not then no worries. I'll just close the issue and move onto Abyss lol sorry for being so active and pushy.

**Comment by Sora3100** [comment]
I've tried it and unfortunately it doesn't seem to add the arte to their pool

**Comment by LeonTrifang** [comment]
Well, it makes sense. I assume you'd have to dive deep into the files to do that, but hey you've done a lot already with all we have. I tried Abyss, but the game straight crashes on spell use even for Asch who has a spell animation haha so Graces and Xillia 2 work for what I want. 

Oh! Sorry one final things and I'll leave you alone, When adding spells to characters in Vesperia, the audio files are attached, I assume you have to go into the files to do this, but I tried messing with the other options for the arte, and it seems the artes you edit reset when you reload the game, so is there anyway to detatch the audio from character spells like Estell's First Aid?

**Comment by Sora3100** [comment]
You would have to edit the arte script in Vesperia, which is pretty much at the end of the file iirc

For Xillia 2, yes and yes it does not, but in the case of that game, I actually know what tells the game not to add them, as evidenced by the "CHR script V2" script

**Comment by LeonTrifang** [comment]
Wait at the end of each file in the cheat engine or the files in the actual game? Cause I can work with either.

Wait so an alium orb edit is possible then? I wouldn't be opposed to making it myself if you can point me in the right direction.

**Comment by Sora3100** [comment]
Files in the actual game as the game unloads them the moment they're unneeded

Yes, it's in the upcoming version of my table, although missing additional effects
I can drop it here for the time being, it's under notes
[Xillia_2.zip](https://github.com/Sora3100/Tales_of_Cheat_Tables/files/13999443/Xillia_2.zip)

**Comment by LeonTrifang** [comment]
I'll just need to find the right files, I think they are under the svo files. I need to unpack them and look through stuff. I am still new to all this, but you've really helped a ton, sorry for bothering so much.

Oh wow that's so kind of you! Seriously I'll have fun messing with this!

**Comment by LeonTrifang** [comment]
Honestly hearing that you are still working on these makes me beyond happy, I'd be honored if you'd be willing to chat more, but I don't think the issues section is the best place to, I feel like there are tons I could learn from you! My biggest modding project was Dragon Quest 11, I worked with so many of the files and made tons of pak based mods, so that is what I am used to. I am beyond willing to learn given the right tools. Either way, it was seriously an honor to talk to you!

**Comment by Sora3100** [comment]
I would recommend the [Tales of ABCDE Discord](https://discord.gg/FSp9DG3Fbg) for Tales related modding/hacking

**Comment by LeonTrifang** [comment]
NO WAY! I HAVE BEEN LOOKING FOR A TALES MODDING DISCORD YOU HAVE NO IDEA HOW HUGE THIS IS THANK YOU SOOOOOO MUCH! HONESTLY THANK YOU!

**Comment by LeonTrifang** [comment]
Sorry I meant to close this. Thanks again for all your help!
