### ISSUE TITLE
Arte Properties

### ISSUE THREAD

**Issue by LeonTrifang** [Sora3100/Tales_of_Cheat_Tables#75]
Hi there! Me again, I've been messing around with lots of stuff lately. Arte Property editors are great! I understand them decently and even figure out some things about Grace's. You see the ? under Arte Effect? I'm sure you figured this out already, but the number given indicates what type of arte it is to the AI, example being 32 will tell the ai it is a healing spell and will cause those with the proper ai (such as Hubert) that he should use it when allies are low. 64 tells them it is an aliment healing spell. Anyway, I just wanted to share this and ask a question. Is there any way to make arte edits permanent? They stick around if you load your game while still playing, but if you restart the game, the edits vanish no matter what file you load. Sorry if this is easy to figure out, but I messed around and couldn't figure it out. Also my guess for the ? above "pointer to name" is the radius of the spell, though that's not too clear sorry.

![image](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/1dba0b40-204e-4490-8281-8e3c4c4ab46f)

![image](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/2349ee81-bafa-4849-b0d8-0bf193269b6d)

**Comment by Sora3100** [comment]
Thanks for your findings, updated the table to reflect the ally thing. The one above the name doesn't seem to be that, changing it for resurrection for example does not give it a larger area.

As for it staying on restart, you can either write a patch for rpcs3 (the harder way) that does it automatically, or make changes to the files directly.

**Comment by LeonTrifang** [comment]
Thanks a ton! So the arte editor is always temp I understand now. I didn't go too indepth finding all the numbers for the ai spells, but I can't remember seeing any others that register different effects. 

Oh! Before I close this, I was wondering how your progress on the Xillia Orb editor is going. I messed around with it myself, but I am sooooo excited for when you release the full thing! Honestly it's an honor that you respond to me haha! Thanks again, if you don't wanna tell your progress I understand, I'll close everything up, but it's been so awesome getting to use your tables!

**Comment by LeonTrifang** [comment]
Hmm? Maybe I missed something, you still have some question marks on the alimium orb thingie. I think it was called Growth Data? 

Yeah there it is. Ignore the "Array of bite??" and others on the right, I opened it without the game on just to check xD but anyway I tried messing about with this, but it seems I am either missing something or it is incomplete. I am not the best at cheat engine at the moment, still learning it so I very well may be just not understanding, but it doesn't seem to work as I expected. It unlocked First Aid for Ludger, but didn't actually add it when I did it how I thought it went. Sorry if it's done and I am just lacking how to do it.

![image](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/4bcb9ba2-6cb6-434d-8849-9ea350ede58f)

![image](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/da597943-ebbd-47df-a0af-146b040c7d68)

**Comment by Sora3100** [comment]
I do not believe the question marks are used for anything there. As for artes and skills, that is because they have a whitelist for both.
If you look at the chr script you can see I edit that.
As for skills, it is located in skill properties

**Comment by LeonTrifang** [comment]
Sorry, I should have just booted it instead of being lazy. Let me explain better sorry. 

Sorry if you know, but what I am trying to figure out is the Growth Data, the part that allows you to (from what I gathered) add skills and spells to the character's list as if they learned it naturally. Doing so it seems you pick which skill or arte you want to replace the one they will learn, but it doesn't seem like I can pick the Extractor that it affects. On top of that, it doesn't seem to change when you change your extractor. Again I am so sorry if I am just wasting your time, but if I am doing this wrong I am more than willing to learn.

Also the ? is on the ID part which made me think it wasn't done yet. What I am trying to do is make it so Ludger can learn spells naturally since he can use the animations for them with his swords, but when I tried to teach him First Aid it showed that he learned it in the victory screen, but it didn't place it on his list. So I am wondering if I am just confused on what this can do, or if I didn't do it right. Also sorry for all the pics.

![image](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/bf5cec0c-5b46-43e8-85e8-cd6acdf26484)

![image](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/c3ada22d-eea0-4fca-ad4d-1798dd2d134e)

![2024-02-05 20_33_39-Greenshot](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/eda988c8-4477-460c-8c84-71a98b3a1dba)

![2024-02-05 20_31_55-Greenshot](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/c37ec6c0-92c8-4ac7-abb6-46c80fa40cec)

![2024-02-05 20_32_11-Greenshot](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/156885683/e58e70cb-dd42-4e79-b8d7-466b2e84f8f3)

**Comment by LeonTrifang** [comment]
Oh wait the whitelist! I remember you mention in the cheat engine. do you mean the edit part at the top that mentions what number each character ends in? I am supposed to put that number somewhere or do something with it? Again sorry I thought that seemed odd, so long story short, the whitelist tells who can learn what, and there is a way to get past that? Or are you trying to say there isn't? Sorry!

**Comment by LeonTrifang** [comment]
Oh yeah okay, that is changing things when I put the numbers in. That makes sense I was a dork for not thinking to use the numbers, I am so sorry!

**Comment by Sora3100** [comment]
You can edit the whitelist yes, but that is not a feature of the table.

**Comment by LeonTrifang** [comment]
I am guessing you have to go into the actual files. Is there any advice you can give or point me in the direction where I can learn how? I am beyond willing to learn this, you've done so much already! I can ask around the discord server you showed me too, but if there is any advice you have I would be beyond honored! If not, I'll go ahead and close everything up, either way thank you so much and sorry for not reading properly!

**Comment by Sora3100** [comment]
No need to go into files if you know how CE works

If you mean to want to change the arte whitelist, I'd recommend going into the script of the chr script, from there its mostly just a list of artes with some extra info like what direction should normals be input as (and an offset to some data section that I do not understand, but the game also doesnt seem to read it when I was looking at it)

**Comment by LeonTrifang** [comment]
Hmm... So just to be clear, the whitelist is an actual part of the game that tells it who is allowed to learn what, and if somehow someone learns something they aren't supposed to, it simply doesn't put it on their list. 

Sadly I don't know too much about CE, but I should be able to basically take each spell and set it to where Ludger can learn it by going into the CHR script? I am guessing each character has a number (maybe the one in the edit section of the growth data?) and changing whatever number the arte is associated with should do the trick right?

**Comment by Sora3100** [comment]
No it is in a completely different area, it is quite literally a list of every arte they can use

**Comment by LeonTrifang** [comment]
Oh wait that is even better, that just means I'd have to replace or add to it, and I wouldn't mind completely replacing each of his sword artes with spells. Do you know which area the list is in? I don't mean to ask so much, but I am so close thanks to you, seriously thank you!

**Comment by Sora3100** [comment]
Search for something like FPS_BTL_UNIT_RUT

**Comment by LeonTrifang** [comment]
Dang it, I gotta take care of something first, hey I know this might be too forward, but is there any other way to contact you? It doesn't have to be anything personal, it can be something simple like your twitter or something, I just don't wanna keep this open when it's practically solved it's just up to me to figure it out, but beyond being able to talk about this stuff, just having another tales fan that I can talk to, and one who clearly loves the tales series this much would be really awesome!

**Comment by Sora3100** [comment]
I am on the discord that you mentioned, just under a different name

**Comment by LeonTrifang** [comment]
Hahaha I'll go ahead and do a scavenger hunt, try to see what similarities the two accounts have. Well it's comforting either way. I can do this thanks to you. Just gotta figure out where to put that thingie in to search. I admit I barely know anything, but you've done so much here it's insane. I'll figure this out best I can! Thanks again!
