### ISSUE TITLE
Question about ToX2

### ISSUE THREAD

**Issue by Avalonere** [Sora3100/Tales_of_Cheat_Tables#76]
Above all, thanks for this absolutely brilliant work!
I was having fun with the playing as a boss function in x1 and x2, which is really really amazing, but I found that in x2, it seems that there's no option for transforming into Pluto (the secret superboss). (I found he is listed in the enemies and artes) Golden knight mage is in x1, just wondering if there's a possibility to add Pluto in? That big guy looks cool.
Thank you again.

**Comment by Sora3100** [comment]
Thereotically, any enemy is playable in X1 or X2, you just gotta find their codes and then apply them as a script (for convenience) or in the debug part of the script. You can more or less get the required values from enemy data book editor, using the offsets.

**Comment by Avalonere** [comment]
Understood, thanks.
