### ISSUE TITLE
xillia2 table don't work enable botton

### ISSUE THREAD

**Issue by celegend** [Sora3100/Tales_of_Cheat_Tables#77]
![20240224_145148](https://github.com/Sora3100/Tales_of_Cheat_Tables/assets/161107635/5c1205a0-b38c-4a37-8172-ca4486dcaac0)

I am playing xillia2 using rog ally. 

Until a few months ago, cheats through the cheat table worked, but this message is displayed and the cheat enable button does not work.

my rpcs3 builid's 0.0.30-16132

**Comment by Sora3100** [comment]
You have to wait a bit after you start the game for it to work.

Since you closed this, I assume you have solved it?

**Comment by celegend** [comment]
sorry. I read the uploaded file. If you set it as written in the file, it will be applied normally again. I'm apologize for raising an issue with information that was already known.
메시지 ID: <Sora3100/Tales_of_Cheat_Tables/issues/77/1962420558 @ github . com>
