### ISSUE TITLE
Xillia Patches not working

### ISSUE THREAD

**Issue by Roctose** [Sora3100/Tales_of_Cheat_Tables#83]
I activate the patches in the version of the emulator that is compatible with cheat engine, but they don't actually work in-game. They show in the menu with the check boxes, but the difficulties won't unlock and mystic artes don't activate. Should specify as well this is for Xillia 1.

**Comment by Sora3100** [comment]
I'm unsure on what you mean the difficulties don't work. You need to change New Game+ to 1 (or 2) for them to unlock in the options screen, or directly change it with difficulty finder.
As for Mystic Artes, I don't even know anything in CE that would activate them. Are you by chance referring to the RPCS3 patches? You need to copy them into a file called "imported_patch.yml" for them to work.

**Comment by Sora3100** [comment]
Is this still an issue?
